
services:
  db:
    image: postgres:14
    container_name: hypervisor_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hypervisor_network

  redis:
    image: redis:alpine
    container_name: hypervisor_redis
    ports:
      - "6379:6379"
    networks:
      - hypervisor_network

  web:
    build: .
    container_name: hypervisor_web
    command: gunicorn hyper_project.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - hypervisor_network

  celery:
    build: .
    container_name: hypervisor_celery
    command: celery -A hyper_project worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - hypervisor_network

  celery-beat:
    build: .
    container_name: hypervisor_celery_beat
    command: celery -A hyper_project beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - hypervisor_network

volumes:
  postgres_data:

networks:
  hypervisor_network:
