# Generated by Django 4.2 on 2024-12-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('total_ram', models.IntegerField()),
                ('total_cpu', models.IntegerField()),
                ('total_gpu', models.IntegerField()),
                ('available_ram', models.IntegerField()),
                ('available_cpu', models.IntegerField()),
                ('available_gpu', models.IntegerField()),
            ],
        ),
    ]
